name: 'Setup .NET Environment'
description: 'Common setup for .NET projects including checkout, .NET setup, and Git configuration'
author: 'AGI.Captor Team'

inputs:
  fetch-depth:
    description: 'Git fetch depth for checkout'
    required: false
    default: '1'
  dotnet-quality:
    description: '.NET quality channel (ga, preview)'
    required: false
    default: 'preview'
  dotnet-version:
    description: '.NET version to install'
    required: false
    default: '9.0.x'

runs:
  using: "composite"
  steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        
    - name: 🔧 Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        dotnet-quality: ${{ inputs.dotnet-quality }}
        
    - name: ⚙️ Configure Git safe.directory
      shell: bash
      run: |
        git config --global --add safe.directory /github/workspace
        git config --global --add safe.directory $(pwd)