name: Reusable Multi-Platform Build

# Reusable multi-platform build workflow
on:
  workflow_call:
    inputs:
      configuration:
        type: string
        required: false
        default: 'Release'
      platforms:
        type: string
        required: false
        default: '["win-x64", "linux-x64", "osx-x64", "osx-arm64"]'
      create-packages:
        type: boolean
        required: false
        default: true
      artifact-retention-days:
        type: number
        required: false
        default: 7

env:
  DOTNET_VERSION: '9.0.x'
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-matrix:
    name: 🚀 Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: win-x64
            os: windows-latest
          - platform: linux-x64
            os: ubuntu-latest
          - platform: osx-x64
            os: macos-13
          - platform: osx-arm64
            os: macos-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        
    - name: 🛠️ Setup Environment
      uses: ./.github/actions/setup-environment
        
    - name: 🚀 Publish and Package
      uses: ./.github/actions/publish-package
      with:
        runtime-id: ${{ matrix.platform }}
        configuration: ${{ inputs.configuration }}
        package: ${{ inputs.create-packages }}
        
    - name: 📦 Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.platform }}
        path: artifacts/publish/${{ matrix.platform }}/
        if-no-files-found: warn
        retention-days: ${{ inputs.artifact-retention-days }}