name: create-release-tag

on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Mark release as prerelease'
        required: false
        default: 'false'

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Validate locked version
        id: set-version
        run: |
          if [ ! -f version.json ]; then
            echo 'version.json missing. Run nuke UpgradeVersion first.' >&2
            exit 1
          fi
          VERSION=$(jq -r '.version' version.json)
          # Pattern: YYYY.(month+day).(hour+mmss)
          # month+day: 3-4 digits; hour+mmss: 5-6 digits
          # Regex stricter: Year '.' (month+day 3-4 digits) '.' (hour+mmss 5-6 digits)
          if ! echo "$VERSION" | grep -Eq '^[0-9]{4}\.[1-9][0-9]{2,3}\.[0-9]{1,2}[0-9]{4}$'; then
            echo "Invalid version format: $VERSION" >&2
            exit 1
          fi
          echo "Using version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Run CheckVersionLocked
        run: |
          ./build.sh CheckVersionLocked

      - name: Ensure tag not exists
        run: |
          TAG=v$VERSION
          # Local check
          if git rev-parse -q --verify refs/tags/$TAG >/dev/null; then
            echo "Tag $TAG already exists locally" >&2
            exit 1
          fi
          # Remote check (race-safe)
          if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists on remote" >&2
            exit 1
          fi

      - name: Create tag
        run: |
          TAG=v$VERSION
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.set-version.outputs.version }}
          name: AGI.Captor v${{ steps.set-version.outputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          body: |
            Release v${{ steps.set-version.outputs.version }}

            Source locked by version.json.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}