name: verify-version

on:
  pull_request:
    branches: [ main, release ]

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: 🔧 Setup .NET Only
        uses: ./.github/actions/setup-dotnet-only
        with:
          dotnet-version: '9.0.x'
          dotnet-quality: 'preview'

      - name: Validate version.json exists
        shell: pwsh
        run: |
          if (-not (Test-Path version.json)) {
            Write-Host "version.json missing. Run 'nuke UpgradeVersion' and commit." -ForegroundColor Red
            exit 1
          }

      - name: Run CheckVersionLocked target
        shell: pwsh
        run: ./build.ps1 CheckVersionLocked

      - name: Detect direct csproj version edits (PR only)
        if: github.event_name == 'pull_request'
        shell: pwsh
        run: |
          # If csproj version tags changed without version.json change -> fail
          $changedCsproj = git diff --name-only origin/${{ github.base_ref }}...HEAD | Where-Object { $_ -match '\.csproj$' }
          if ($changedCsproj) {
            $versionJsonChanged = git diff --name-only origin/${{ github.base_ref }}...HEAD | Where-Object { $_ -eq 'version.json' }
            if (-not $versionJsonChanged) {
              Write-Host "❌ Detected .csproj change(s) without version.json update:" -ForegroundColor Red
              $changedCsproj | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
              exit 1
            }
            # If both changed, ensure version.json timestamp version increments vs base
            $baseVer = ""
            try { $baseVer = git show origin/${{ github.base_ref }}:version.json | ConvertFrom-Json | Select-Object -ExpandProperty version } catch { }
            $newVer = (Get-Content version.json | ConvertFrom-Json).version
            if ($baseVer -and ($baseVer -eq $newVer)) {
              Write-Host "❌ version.json not updated (same version) though .csproj modified." -ForegroundColor Red
              exit 1
            }
            Write-Host "✅ Version consistency check passed" -ForegroundColor Green
          }

      - name: Summary
        shell: pwsh
        run: Write-Host "✅ Version verification passed." -ForegroundColor Green